language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  - DEPS=normal
  - DEPS=highest
  - DEPS=lowest

matrix:
  fast_finish: true

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.composer/cache

before_install: travis_retry composer selfupdate --preview

install:
- if [ "$DEPS" = "normal" ]; then travis_retry composer install --no-interaction; fi;
- if [ "$DEPS" = "highest" ]; then travis_retry composer update --no-interaction; fi;
- if [ "$DEPS" = "lowest" ]; then travis_retry composer update --no-interaction --prefer-lowest --prefer-stable; fi;

before_script:
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - test -e build/logs/clover.xml && wget https://scrutinizer-ci.com/ocular.phar
  - test -e build/logs/clover.xml && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
